language: perl
perl:
  - "5.32.0"
  - "5.28"
  - "5.24"
  - "5.16"
  - "5.10.1"
before_install:
  # Show Location
  - >
    echo "USER: " $(whoami) ; 
    echo "HOME: '$HOME'" ; 
    pwd ; 
    ls -lah ;
  # List pre-installed Perl Packages
  - dpkg --get-selections | grep -i perl | sort
  # Install missing Packages with apt-get
  - echo "apt-get - Install missing Packages"
  - sudo apt-get update && sudo apt-get install libdata-dump-perl libcapture-tiny-perl
  - >
    if [ "$TRAVIS_PERL_VERSION" == "5.10.1" ]; then 
    sudo apt-get install liblocal-lib-perl libmodule-build-perl libextutils-config-perl libextutils-helpers-perl libextutils-installpaths-perl ;
    sudo apt-get install libhttp-tiny-perl ;
    fi
  - echo "cpanm - Install missing Packages"
  - perlbrew available
  - perlbrew list
  # Do Perl 5.10 Installation
  - >
    if [ "$TRAVIS_PERL_VERSION" == "5.10.1" ]; then 
    cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib) ;
    perl -Mlocal::lib ;
    cpanm -v --installdeps --with-feature=test_perl-5.10 . ; 
    /home/travis/perl5/bin/perl-build --definitions ;
    /home/travis/perl5/bin/perl-build 5.10.1 ~/perl5/perlbrew/perls/perl-5.10.1 && perlbrew switch 5.10.1 ; 
    perl -v ;
    fi
