language: perl
perl:
  - "5.32.0"
  - "5.28"
  - "5.24"
  - "5.16"
before_install:
  # List pre-installed Perl Packages
  - dpkg --get-selections | grep -i perl | sort
  # Install missing Packages with apt-get
  - echo "apt-get - Install missing Packages"
  - sudo apt-get update && sudo apt-get install libdata-dump-perl libcapture-tiny-perl
  # Show Location
  - pwd && ls -lah
  - echo "cpanm - Install missing Packages"
  - perlbrew available
  - perlbrew list
