language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.16"
  - "5.10"
before_install:
  # List pre-installed Perl Packages
  - dpkg --get-selections | grep -i perl | sort
  # Install missing Packages with apt-get
  - echo "apt-get - Install missing Packages"
  - sudo apt-get update && sudo apt-get install libdata-dump-perl libcapture-tiny-perl
  # Show Location
  - pwd && ls -lah
  - echo "Install missing Packages"
