# This is a basic workflow to help you get started with Actions

name: Run configured Tests from the Test Directory

# Controls when the action will run. Triggers the workflow pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Configure and Run the Testing Job
  testing:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Install missing Perl Libraries
      - name: Install Capture::Tiny Library
        run: sudo apt-get update && sudo apt-get install libcapture-tiny-perl
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Starting Test Sequences
        run: echo "Starting Test Sequences"

      - name: Listing Directory Contents
        run: pwd && ls -lah
        
      # Test the Process::SubProcess Package
      - name: Process::SubProcess Package Tests
        run: t/test_subprocess.t
      # Perfomance Tests on Process::SubProcess Package
      - name: Process::SubProcess Package Performance Tests
        run: t/test_performance.t
      # Test the Process::SubProcess::Group Package
      - name: Process::SubProcess::Group Package Tests
        run: t/test_group.t

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
